using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class FollowPlayer : MonoBehaviour
{
    public GameObject player;
    // Declaramos la posici칩n de la
    // c치mara justo como la tenemos en Unity
    private Vector3 offset = new Vector3(0, 6, -7); 

    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void LateUpdate()
    {
        // Se modifica la posci칩n de la
        // c치mara de nuestro jugador agregando el offset para que
        // se vea desde una perspectiva de arriba 
        transform.position = player.transform.position + offset; 

    }
}